# Generated by Django 5.2.8 on 2025-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicinsights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
